platform :ios, '12.0'

use_frameworks!

workspace 'ZWallet'

def common_dependency
	pod 'Kingfisher'
end

target 'App' do
  pod 'Moya'
  pod 'netfox', :configurations => ['Debug']
  common_dependency
end

target 'Core' do
	project '../Module/Core/Core'

	pod 'Moya'
	common_dependency
end

target 'History' do
	project '../Module/History/History'

	common_dependency
end

target 'Home' do
	project '../Module/Home/Home'

	common_dependency
end

target 'Login' do
	project '../Module/Login/Login'
end