platform :ios, '11.0'

use_frameworks!

workspace 'ZWallet'

def common_dependency
	pod 'Kingfisher'
end

target 'App' do
  pod 'Moya'
  pod 'netfox', :configurations => ['Debug']
  common_dependency
end

target 'Core' do
	project '../Module/Core/Core'

	pod 'Moya'
	common_dependency
end

target 'Login' do
	project '../Module/Login/Login'
end

target 'Register' do
	project '../Module/Register/Register'
end

target 'PINActivation' do
	project '../Module/PINActivation/PINActivation'
end

target 'ConfirmOTP' do
	project '../Module/ConfirmOTP/ConfirmOTP'
end

target 'Home' do
	project '../Module/Home/Home'

	common_dependency
end

target 'History' do
	project '../Module/History/History'

	common_dependency
end

target 'Receiver' do
	project '../Module/Receiver/Receiver'

	common_dependency
end

target 'Transaction' do
	project '../Module/Transaction/Transaction'

	common_dependency
end

target 'ConfirmTransaction' do
	project '../Module/ConfirmTransaction/ConfirmTransaction'

	common_dependency
end

target 'TransactionDetail' do
	project '../Module/TransactionDetail/TransactionDetail'

	common_dependency
end

target 'PINConfirmation' do
	project '../Module/PINConfirmation/PINConfirmation'

	common_dependency
end