disabled_rules:
  - comma
  - force_cast
  - force_try
  - large_tuple
  - nesting
  - function_parameter_count
  - trailing_whitespace

line_length:
  warning: 240
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
